server:
  port: 18888
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
    context-path: /admin
  undertow:
    buffer-size: 1024
    direct-buffers: true

spring:
  web:
    resources:
      add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: auth
  datasource:
    hikari:
      pool-name: auth-datasource
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: select 1
  profiles:
    active: dev

mybatis-flex:
  mapper-locations:
    - classpath*:/mapper/*.xml

# sa-token
sa-token:
  token-name: authToken
  # ????
  timeout: 2592000
  # ????
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: random-64
  is-log: true

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.auth.web
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn